---
title: AÉDIROUM
baseurl: http://aediroum.iro.umontreal.ca/
theme: aediroum

# Menu
menu:
  main:
    - Name: Évènements
      Identifier: evenements
      Weight: 3
    - Name: Documents
      Identifier: documents
      Weight: 4

# Markdown
blackfriday:
  angledQuotes: true
  hrefTargetBlank: true

# Crawling
sitemap:
  changefreq: monthly
  priority: 0.5
enableRobotsTXT: true
disableHugoGeneratorInject: true

# Langue
defaultContentLanguage: fr
languageCode: fr

# Divers
metaDataFormat: yaml
# canonifyURLs: true
paginate: 5
# ignoreFiles: [".scss$"]
