---
title: AÉDIROUM
baseurl: http://aediroum.iro.umontreal.ca/
theme: aediroum

# Menu
menu:
  main:
    - Name: Évènements
      Identifier: evenements
      Weight: 4
    - Name: Documents
      Identifier: documents
      Weight: 5

# Markdown
blackfriday:
  angledQuotes: true
  hrefTargetBlank: true

# Crawling
sitemap:
  changefreq: monthly
  priority: 0.5
enableRobotsTXT: true
disableHugoGeneratorInject: true

# Language
defaultContentLanguage: fr
languageCode: fr

# Miscellaneous
metaDataFormat: yaml
paginate: 5
