---
title: AÉDIROUM
baseurl: http://aediroum.iro.umontreal.ca/
theme: aediroum

menu:
  main:
    - Name: Évènements
      Identifier: evenements
      Weight: 3
    - Name: Documents
      Identifier: documents
      Weight: 4

sitemap:
  changefreq: monthly
  priority: 0.5

defaultContentLanguage: fr
metaDataFormat: yaml
canonifyURLs: true
enableRobotsTXT: true
disableHugoGeneratorInject: true

blackfriday:
  angledQuotes: true
  hrefTargetBlank: true
