title: AÉDIROUM
baseurl: http://aediroum.iro.umontreal.ca
theme: aediroum

# Menu
menu:
  main:
    - Name: Évènements
      Identifier: evenements
      Weight: 4
    - Name: Documents
      Identifier: documents
      Weight: 5

# Language
defaultContentLanguage: fr
languageCode: fr

# Markdown
blackfriday:
  angledQuotes: true

# Crawling
enableRobotsTXT: true
disableHugoGeneratorInject: true

# Miscellaneous
metaDataFormat: yaml
paginate: 5
