---
title: AÉDIROUM
baseurl: http://aediroum.iro.umontreal.ca/
theme: aediroum
defaultContentLanguage: fr
metaDataFormat: yaml
enableRobotsTXT: true
disableHugoGeneratorInject: true
blackfriday:
  angledQuotes: true
